### ISSUE TITLE
Задание для 4 ПК(Женя)

### ISSUE THREAD

**Issue by GIGANEKIT** [GIGANEKIT/ZadanieNa2Parii#4]
Склонировать репозиторий(не забудь запушить).
Создать новую папку - назвать "Папка 4".
В этой папке создать еще 18 папок при помощи СКРИПТА.
В каждой из этой папки создать 15 файлов при помощи КОМАНДЫ в терминале.
В каждом файле должны быть 3 популярные марки машины и по 5 примеров каждой марки(оформи аккуратно).
Создай новую ветку и назови ее - CloneCars.
В этой ветке создай папку "CloneCars" - и скопируй туда ТОЛЬКО файлы из папок.
Удали ветку main или masters(смотря что у тебя).
Запушь все на GitHub
В итоге у тебя должна быть 1 ветка CloneCars в которой все данные main и папка Clone.
Удачи)

**Comment by CMEKAJIo4ka** [comment]
Кто такой скрипт и чем он отличается от команды
