### ISSUE TITLE
Задание 2 для ПК 4(Женя)

### ISSUE THREAD

**Issue by GIGANEKIT** [GIGANEKIT/ZadanieNa2Parii#8]
Остаться в том же репозитории.
Создать папку 24JS и в ней создать файл JSWhile.
В этом файле реализовать цикл while.
Вывести столбиком числа от 1 до 200.
Создать новый файл JSFor.
В этом файле реализовать цикл for.
Вывести на экран только НЕ четные числа от 1 до 200.
Новый файл JSMassive.
В этом файле реализовать работу с массивами.
Дан массив с элементами [1,2,2,52,5,6,37,3,3,6]. C помощью цикла вывести массив на экран
Удачи!

**Comment by CMEKAJIo4ka** [comment]
А где я эти числа должен вывести
